name: live_location
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.2.0
  location: ^4.4.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  permission_handler: ^10.0.0
  firebase_auth: ^3.7.0
  flutter_map: ^2.2.0
  cached_network_image: ^2.0.0
  latlong2: ^0.8.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/tt_logo.png

